### ISSUE TITLE
Why decompose matrix column-wisely?

### ISSUE THREAD

**Issue by namezhenzhang** [catid/dora#4]
Hi,
I notice the weight matrix is decomposed into magnitude and direction components column-wisely.

My understanding is that in the linear transformation y = W * x, each row of the weight matrix W corresponds to the weights for a particular output dimension, and the dot product of each row of W with the input vector x produces one element of the output vector y. Therefore, I would expect the decomposition to be performed row-wise rather than column-wise.

Could you please provide more insights into why the decomposition is performed column-wise (i.e., along the input dimension) for the magnitude component? How does this align with the intuition of the linear transformation and the adaptation of the direction component along the output dimension?

Thank you so much!

**Comment by catid** [comment]
Your insight seems correct to me.  I think I just messed it up.

**Comment by catid** [comment]
Okay so I tried changing `norm = adapted.norm(p=2, dim=0, keepdim=True)` to `norm = adapted.norm(p=2, dim=1, keepdim=True)` but the final loss becomes extremely high if I do this.  So the current code is right.

But, the question is why?  My code is consistent with the paper:

![image](https://github.com/catid/dora/assets/252193/6fa10a31-4421-4fe3-898f-33de1edc2512)

It's just how the math works out.
