### ISSUE TITLE
Slight error?

### ISSUE THREAD

**Issue by sairaamspage** [catid/dora#6]
Hi,
firstly, your implementation of the paper is very cool!

Just wanted to point out that self.m should be initialised to the norm of the old model's matrix. I am not sure if that is happening here.

**Comment by catid** [comment]
Taking a look just noticed this..

**Comment by catid** [comment]
Yes this is going on here:

```
self.m = nn.Parameter(self.weight.norm(p=2, dim=0, keepdim=True))
```
